steps:
# Install DICOMFuse
- name: 'maven:3.6.1-jdk-8'
  args:
  - 'mvn'
  - 'install'
# Run integration tests
- name: 'google/cloud-sdk:272.0.0'
  args:
  - 'bash'
  - './build/build.sh'
  - '${_STAGE}'
  - '${_PROJECT}'
  - '${_LOCATION}'
  - '${_DATASET}'
  - '${_MAX_STUDY_STORE}'
  - '${_LAST_STUDY}'
  timeout: 600s

substitutions:
  _STAGE: v1beta1
  _PROJECT: gcp-healthcare-oss-test
  _LOCATION: us-central1
  _DATASET: healthcare-api-dicom-fuse-test
  _MAX_STUDY_STORE: retrieve-study-past-max-studies-limit
  _LAST_STUDY: '11432'
